
# personal information

author: YangBo

description: 长期不懂设计的Web开发

# 头像url
avatar: "/img/avatar.png"

# 开启头像动画效果
animate: true

favicon: "/img/favicon.ico"

# nav
nav:
  首页: /
  文章归档: /archive
  作品: /work
  相册: /photo
  留言: /comment

# about
about: 于技术而言，我已经知道什么重要，什么不重要；于人生而言，我知道自己现在想要什么，也知道自己在可以预见的未来想要什么。


# 社交网站
social:
  github: "https://www.github.com/idbord"
  facebook: "https://www.github.com/idbord"
  weibo: "https://www.github.com/idbord"
  envelope-o: "https://www.github.com/idbord"
  google: "https://www.github.com/idbord"
  weixin: "https://www.github.com/idbord"
  rss: "https://www.github.com/idbord"

friend_link: true

friends:
  邓露艺: "https://www.hellflame.net"
  李小宇: "https://lee3164.github.io"


# 评论
comment: true

# 多说
duoshuo: idbord